### ISSUE TITLE
User Request: Self-signed certificates generated through Helm

### ISSUE THREAD

**Issue by nikos912000** [DataDog/chaos-controller#358]
**Is your feature request related to a problem? Please describe.**
Internally we don't have the `cert-manager` installed in certain clusters which required us to [configure the admission hook](https://github.com/DataDog/chaos-controller/blob/main/docs/installation.md#admission-webhook).

There are many ways to generate certificates but it'd be nice to provide a solution that works out-of-the-box for both cases in the charts; when the cert-manager is installed and when it is not.

**Describe the solution you'd like**
I added some logic to our internal charts to support that by setting a property `certManager.enabled` in the `values.yaml`. When the cert-manager is not installed we use [Helm template functions](https://helm.sh/docs/chart_template_guide/function_list) to generate the certificates. This is very similar to the [kubefed webhook implementation](https://github.com/kubernetes-sigs/kubefed/blob/master/charts/kubefed/charts/controllermanager/templates/webhook.yaml).

Would you be open to a PR for that? The only problem I can think of is that this is Helm-specific.

**Comment by Devatoria** [comment]
I don't see any issue for this to be helm specific. The chart we provide is an All-in-One chart that can be used to deploy the controller but it can be totally customized when needed. To be honest, we are not using it internally and we have our own chart for the exact same reasons as you (we do not use cert-manager).

We are totally open to a PR that would make this a bit more generic. We chose cert-manager because it is the one used in the examples of the kubebuilder documentation.

**Comment by nikos912000** [comment]
Cool. I'm not sure if there is a way to assign this issue to me but I'll raise a PR by next week.

**Comment by nikos912000** [comment]
Closing this as the changes have been merged.
