### ISSUE TITLE
User Issue: :latest tag did not work for datadog/chaos-injector, but :4.2.1 did

### ISSUE THREAD

**Issue by sabinecodes15** [DataDog/chaos-controller#393]
**Describe the bug**
While trying to use the `container_failure_all_forced.yaml` disruption, the pod created to inject the disruption failed to pull the image from Docker Hub. Adding the tag `:4.2.1` to `image: datadog/chaos-injector` in the install.yml file resolved this.

**To Reproduce**
1. Do `kubectl apply -f https://raw.githubusercontent.com/DataDog/chaos-controller/main/chart/install.yaml` on the master node of a cluster.
2. Download the [disruption](https://github.com/DataDog/chaoscontroller/blob/main/examples/container_failure_all_forced.yaml)  and apply with `kubectl apply -f container_failure_all_forced.yaml`
3. Do `kubectl get pods --all-namespaces` or `kubectl get pods -n chaos-engineering` to view the disruption pod.
4. See the error: Disruption pod failed to pull the image, with a status of ErrImagePull, then ImagePullBackOff

**Expected behavior**
It should have created a running pod with a working container to inject the disruption into the target

**Screenshots**
Events list from `kubectl describe pod <DISRUPTOR-PODNAME> -n chaos-engineering`
<img width="944" alt="2021-08-16 (1)" src="https://user-images.githubusercontent.com/42010139/129625498-f620eb7d-5381-404d-b11a-6724b820f77a.png">

**Environment:**
 - Kubernetes version: v1.21.3+k3s1
 - Controller version:
 - Cloud provider (or `local`): AWS
 - Base OS for Kubernetes: Amazon Linux 2

**Additional context**
Performed on a K3s cluster made up of Amazon EC2 instances, with one master and two worker nodes. The error was encountered while running commands on master.

**Comment by Devatoria** [comment]
Hi and thank you for the feedback. We indeed do not push the `latest` tag for multiple of reasons, but here's the main one:

All images must use the exact same tag to work together, for compatibility reasons (`chaos-controller`, `chaos-injector` and `chaos-handler`). If we publish a new version of images and push the latest tag, you are not ensured that the newly spawned `chaos-injector` pods are using the same version as the `chaos-controller`.

We recently changed the way we configure the controller (through a configmap with configured images and tags instead of flags passed to the container). It seems that we forgot to add the tag here when we generate the `install.yaml` file, this is why it defaults to latest. We'll fix it as soon as possible.

Thanks again!
