### ISSUE TITLE
User Issue: Start in private cluster without public internet access

### ISSUE THREAD

**Issue by xpdable** [DataDog/chaos-controller#844]
**Describe the bug**

kubectl logs -f chaos-controller-5f897979d-fxv9z -n chaos-engineering 

> {"level":"fatal","ts":1710340783015.9324,"caller":"chaos-controller/main.go:154","message":"error initializing CloudProviderManager","error":"could not get the new ip ranges from provider AWS: Get \"https://ip-ranges.amazonaws.com/ip-ranges.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\ncould not get the new ip ranges from provider GCP: Get \"https://www.gstatic.com/ipranges/goog.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\ncould not get the new ip ranges from provider Datadog: Get \"https://ip-ranges.datadoghq.com/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)\n","stacktrace":"main.main\n\t/go/src/github.com/BkfwVXeB/0/DataDog/chaos-controller/main.go:154\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}

We have EKS cluster without Internet access, what would be the correct way to start? I have proxy to Internet, and is there a config to setup it?

**Comment by ptnapoleon** [comment]
The simplest approach is to disable the feature that reaches out to the internet: https://github.com/DataDog/chaos-controller/blob/main/chart/values.yaml#L47

As for solving the networking so that the controller can proxy to the internet, unfortunately that's something I have no experience with at all, and is outside the scope of what we're willing to support.
